[package]
name = "lamba-oksayici"
version = "0.1.0"
edition = "2021"

[dependencies]
tapo = "0.8"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
pretty_env_logger = "0.5"
scrap = "0.5"
image = "0.24"